services:
  postgres_test:
    image: postgres:16-alpine
    container_name: postgres_library_test
    environment:
      POSTGRES_USER: ${POSTGRES_TEST_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_TEST_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_TEST_DB:-mobile_library_test}
    ports:
      - "${POSTGRES_TEST_PORT:-5433}:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  pgdata_test:
    driver: local
