"""Add user_id to borrow table

Revision ID: 002_add_user_id_to_borrow
Revises: 001_add_user_table
Create Date: 2023-09-15 11:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_add_user_id_to_borrow'
down_revision = '001_add_user_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('borrows', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key('borrows_user_id_fkey', 'borrows', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('borrows_user_id_fkey', 'borrows', type_='foreignkey')
    op.drop_column('borrows', 'user_id')
    # ### end Alembic commands ###